version: "3.9"
services:
  server_hub:
    build: .
    environment:
      - PROPAGANDA_ARGS
    ports:
      - "8899:8899"
      - "8889:8889"
      - "8839:8839/udp"
      - "8859:8859"
    volumes:
      - ./logs:/app/logs
