/*
 * RegexPlorer.java
 *
 * Created on den 7 september 2006, 14:43
 */

package com.femtioprocent.fpd.appl;

import com.femtioprocent.fpd.util.ObjectHibernator;
import java.util.HashMap;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author  lars
 */
public class RegexPlorer extends javax.swing.JFrame {
    static boolean sa = false;
    
    /** Creates new form RegexPlorer */
    public RegexPlorer() {
	initComponents();
	restore();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        pan = new javax.swing.JPanel();
        re_cb = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        re_note = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        re_save = new javax.swing.JButton();
        re_rem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_save = new javax.swing.JButton();
        txt_cb = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txt_rem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        isMatched = new javax.swing.JCheckBox();
        isFound = new javax.swing.JCheckBox();
        cg1 = new javax.swing.JTextField();
        cg2 = new javax.swing.JTextField();
        cg3 = new javax.swing.JTextField();
        cg4 = new javax.swing.JTextField();
        cg5 = new javax.swing.JTextField();
        cg6 = new javax.swing.JTextField();
        cg7 = new javax.swing.JTextField();
        cg8 = new javax.swing.JTextField();
        lb1 = new javax.swing.JLabel();
        isError = new javax.swing.JCheckBox();
        cg0 = new javax.swing.JTextField();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        eval = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Regular Expression Explorer");

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        pan.setBorder(javax.swing.BorderFactory.createTitledBorder("Regular Expression"));

        re_cb.setEditable(true);

        re_note.setColumns(20);
        re_note.setRows(5);
        jScrollPane1.setViewportView(re_note);

        jLabel1.setText("Note");

        jLabel2.setText("Regular Expression");

        re_save.setText("Save");
        re_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_saveActionPerformed(evt);
            }
        });

        re_rem.setText("Remove");
        re_rem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_remActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panLayout = new org.jdesktop.layout.GroupLayout(pan);
        pan.setLayout(panLayout);
        panLayout.setHorizontalGroup(
            panLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panLayout.createSequentialGroup()
                .addContainerGap()
                .add(panLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panLayout.createSequentialGroup()
                        .add(re_cb, 0, 522, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(re_rem)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(re_save))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE))
                .addContainerGap())
        );
        panLayout.setVerticalGroup(
            panLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panLayout.createSequentialGroup()
                .addContainerGap()
                .add(panLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(re_save)
                    .add(re_rem)
                    .add(re_cb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Text"));

        txt_save.setText("Save");
        txt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_saveActionPerformed(evt);
            }
        });

        txt_cb.setEditable(true);

        jLabel5.setText("Text input");

        txt_rem.setText("Remove");
        txt_rem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_remActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(56, 56, 56)
                .add(jLabel5)
                .add(20, 20, 20)
                .add(txt_cb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 525, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txt_rem)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txt_save)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txt_save)
                    .add(txt_rem)
                    .add(jLabel5)
                    .add(txt_cb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));

        isMatched.setText("Matched");
        isMatched.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        isMatched.setMargin(new java.awt.Insets(0, 0, 0, 0));

        isFound.setText("Found");
        isFound.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        isFound.setMargin(new java.awt.Insets(0, 0, 0, 0));

        lb1.setText("Capture Groups 1");

        isError.setText("Error");
        isError.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        isError.setMargin(new java.awt.Insets(0, 0, 0, 0));

        lb2.setText("2");

        lb3.setText("3");

        lb4.setText("4");

        lb5.setText("5");

        lb6.setText("6");

        lb7.setText("7");

        lb8.setText("8");

        jLabel14.setText("Found matching text");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel14)
                    .add(lb2)
                    .add(lb3)
                    .add(lb4)
                    .add(lb5)
                    .add(lb6)
                    .add(lb7)
                    .add(lb8)
                    .add(lb1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(isMatched)
                        .add(33, 33, 33)
                        .add(isFound)
                        .add(33, 33, 33)
                        .add(isError))
                    .add(cg2)
                    .add(cg3)
                    .add(cg4)
                    .add(cg5)
                    .add(cg6)
                    .add(cg7)
                    .add(cg8)
                    .add(cg1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .add(cg0))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(isMatched)
                    .add(isFound)
                    .add(isError))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cg0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cg1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lb1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cg2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lb2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cg3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lb3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cg4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lb4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cg5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lb5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cg6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lb6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cg7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lb7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cg8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lb8))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        eval.setText("Evaluate Regular Expression");
        eval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evalActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pan, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(eval)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, close))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(pan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(eval)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(close)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void re_remActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_remActionPerformed
	String txt = re_cb.getSelectedItem().toString();
	saved_re.remove(txt);
	updRE();
	re_cb.setSelectedItem(txt);
    }//GEN-LAST:event_re_remActionPerformed

    private void txt_remActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_remActionPerformed
	String txt = txt_cb.getSelectedItem().toString();
	saved_txt.remove(txt);
	updTxt();
	txt_cb.setSelectedItem(txt);
    }//GEN-LAST:event_txt_remActionPerformed

    private void txt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_saveActionPerformed
	saveTxt();
    }//GEN-LAST:event_txt_saveActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
	save();
	setVisible(false);
	if ( sa )
	    System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void re_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_saveActionPerformed
	saveRE();
    }//GEN-LAST:event_re_saveActionPerformed

    private void evalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evalActionPerformed
	try {
	    JTextField[] cg = new JTextField[8+1];
	    cg[0] = cg0;
	    cg[1] = cg1;
	    cg[2] = cg2;
	    cg[3] = cg3;
	    cg[4] = cg4;
	    cg[5] = cg5;
	    cg[6] = cg6;
	    cg[7] = cg7;
	    cg[8] = cg8;
	    
	    JLabel[] lb = new JLabel[8+1];
	    //lb[0] = lb0;
	    lb[1] = lb1;
	    lb[2] = lb2;
	    lb[3] = lb3;
	    lb[4] = lb4;
	    lb[5] = lb5;
	    lb[6] = lb6;
	    lb[7] = lb7;
	    lb[8] = lb8;
	    for(int i = 1+0; i <= 8; i++) {
		lb[i].setEnabled(false);
	    }

    	    for(int i = 0; i <= 8; i++) {
		cg[i].setText("");
		cg[i].setEnabled(false);
	    }
	    cg0.setText("");
	    isMatched.setSelected(false);
	    isFound.setSelected(false);

	    
	    String re = re_cb.getSelectedItem().toString();
	    String text = txt_cb.getSelectedItem().toString();
	    Pattern pat = Pattern.compile(re);
	    Matcher mat = pat.matcher(text);
	    isMatched.setSelected(mat.matches());
	    mat.reset();
	    isFound.setSelected(mat.find());
	    isError.setSelected(false);
	    
	    
	    int gc = mat.groupCount();
	    for(int i = 0; i <= 8; i++) {
		if ( i > gc ) {
		}
		else {
		    cg[i].setText(mat.group(i));
		    cg[i].setEnabled(true);
		    if ( i > 0 )
			lb[i].setEnabled(true);
		}
	    }
	    cg0.setText(mat.group(0));
	    
	} catch (Exception ex) {
	    isError.setSelected(true);
	    
	}
    }//GEN-LAST:event_evalActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	sa = true;
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new RegexPlorer().setVisible(true);
	    }
	});
    }

    Set<String> saved_re = new TreeSet<String>();
    Set<String> saved_txt = new TreeSet<String>();
    
    void restore() {
	ObjectHibernator<Set<String>> h1 = new ObjectHibernator<Set<String>>("re");
	Set<String> o1 = h1.restoreObject();
	if ( o1 != null )
	    saved_re = o1;
	ObjectHibernator<Set<String>> h2 = new ObjectHibernator<Set<String>>("txt");
	Set<String> o2 = h2.restoreObject();
	if ( o2 != null )
	    saved_txt = o2;
	
	ObjectHibernator<String> h3 = new ObjectHibernator<String>("note");
	String s3 = h3.restoreObject();
	if ( s3 != null )
	    re_note.setText(s3);

	updTxt();
	updRE();
    }
    
    void save() {
	ObjectHibernator<Set<String>> h1 = new ObjectHibernator<Set<String>>("re");
	h1.saveObject(saved_re);
	ObjectHibernator<Set<String>> h2 = new ObjectHibernator<Set<String>>("txt");
	h2.saveObject(saved_txt);
	ObjectHibernator<String> h3 = new ObjectHibernator<String>("note");
	h3.saveObject(re_note.getText());
    }
    
    private void saveRE() {
	try {
	    String re = (String)re_cb.getSelectedItem();
	    saved_re.add(re);
	    updRE();
	    re_cb.setSelectedItem(re);
	} catch (Exception ex) {
	}
	repaint();
    }

    private void saveTxt() {
	String txt = txt_cb.getSelectedItem().toString();
	saved_txt.add(txt);
	updTxt();
	txt_cb.setSelectedItem(txt);
    }
    
    void updTxt() {
	txt_cb.removeAllItems();
	for(String id : saved_txt ) {
	    txt_cb.addItem(id);
	}
    }

    void updRE() {
	re_cb.removeAllItems();
	for(String re2 : saved_re)
	    re_cb.addItem(re2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cg0;
    private javax.swing.JTextField cg1;
    private javax.swing.JTextField cg2;
    private javax.swing.JTextField cg3;
    private javax.swing.JTextField cg4;
    private javax.swing.JTextField cg5;
    private javax.swing.JTextField cg6;
    private javax.swing.JTextField cg7;
    private javax.swing.JTextField cg8;
    private javax.swing.JButton close;
    private javax.swing.JButton eval;
    private javax.swing.JCheckBox isError;
    private javax.swing.JCheckBox isFound;
    private javax.swing.JCheckBox isMatched;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JPanel pan;
    private javax.swing.JComboBox re_cb;
    private javax.swing.JTextArea re_note;
    private javax.swing.JButton re_rem;
    private javax.swing.JButton re_save;
    private javax.swing.JComboBox txt_cb;
    private javax.swing.JButton txt_rem;
    private javax.swing.JButton txt_save;
    // End of variables declaration//GEN-END:variables
    
}
