
package propaganda.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HttpWSService", targetNamespace = "http://server.propaganda/", wsdlLocation = "http://localhost:8877/propaganda?wsdl")
public class HttpWSService
    extends Service
{

    private final static URL HTTPWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException HTTPWSSERVICE_EXCEPTION;
    private final static QName HTTPWSSERVICE_QNAME = new QName("http://server.propaganda/", "HttpWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8877/propaganda?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HTTPWSSERVICE_WSDL_LOCATION = url;
        HTTPWSSERVICE_EXCEPTION = e;
    }

    public HttpWSService() {
        super(__getWsdlLocation(), HTTPWSSERVICE_QNAME);
    }

    public HttpWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HTTPWSSERVICE_QNAME, features);
    }

    public HttpWSService(URL wsdlLocation) {
        super(wsdlLocation, HTTPWSSERVICE_QNAME);
    }

    public HttpWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HTTPWSSERVICE_QNAME, features);
    }

    public HttpWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HttpWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HttpWSServive
     */
    @WebEndpoint(name = "HttpWSServiceSOAPHttpPort")
    public HttpWSServive getHttpWSServiceSOAPHttpPort() {
        return super.getPort(new QName("http://server.propaganda/", "HttpWSServiceSOAPHttpPort"), HttpWSServive.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HttpWSServive
     */
    @WebEndpoint(name = "HttpWSServiceSOAPHttpPort")
    public HttpWSServive getHttpWSServiceSOAPHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.propaganda/", "HttpWSServiceSOAPHttpPort"), HttpWSServive.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HTTPWSSERVICE_EXCEPTION!= null) {
            throw HTTPWSSERVICE_EXCEPTION;
        }
        return HTTPWSSERVICE_WSDL_LOCATION;
    }

}
